nelmio_api_doc:
    documentation:
        info:
            title: Marketplace API
            description: API
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1
